create table PatientRegister (
	PatientId VARCHAR(50) NOT NULL,
	Name VARCHAR(50),
	Age VARCHAR(50),
	Address VARCHAR(50),
	HospitalName VARCHAR(50),
	BranchName VARCHAR(50),
	City VARCHAR(50),
	PRIMARY KEY(PatientId)
);
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('73-9687942', 'Maddalena Gillogley', '06', '85240 Washington Lane', 'Blossom General Hospital', 'Homewood', 'Wanasari Baleran');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('79-1796296', 'Abe Walworche', '28', '55130 Harper Pass', 'Blossom General Hospital', 'Algoma', 'Velingrad');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('23-9923918', 'Magnum Juleff', '72', '8 Butterfield Hill', 'Fairbanks Medical Center', 'Moulton', 'Muang Sam Sip');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('56-2959425', 'Gallard Kabsch', '88', '771 Barnett Alley', 'Fairbanks Medical Center', 'Del Sol', 'Koronowo');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('88-1659026', 'Willette Ollivierre', '54', '522 Butterfield Street', 'Blossom General Hospital', 'Maple Wood', 'Yamoussoukro');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('92-9404628', 'Trenna Windless', '32', '2366 Claremont Circle', 'Fairbanks Medical Center', 'Old Shore', 'Longxing');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('04-2132784', 'Sheilah Cholonin', '61', '2 Schmedeman Avenue', 'Fairbanks Medical Center', 'Towne', 'San Salvador de Jujuy');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('65-3253577', 'Alfy Pichmann', '74', '4250 Troy Court', 'Fairbanks Medical Center', 'Scott', 'Rasskazovo');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('75-9350891', 'Beverlie Orknay', '50', '67 Mayer Center', 'Greengrass Medical Center', 'Messerschmidt', 'Roma');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('76-2462301', 'Lynsey Angerstein', '51', '17553 Heath Trail', 'Progress Hospital Center', 'Northridge', 'Penisihan');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('08-8481190', 'Symon Cluelow', '75', '08800 Susan Plaza', 'Fairbanks Medical Center', 'Pine View', 'Jintian');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('50-5564624', 'Gaynor Carlesso', '32', '735 Sutherland Street', 'Hope Haven Community Hospital', 'Dovetail', 'Mikhaylovsk');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('13-7548249', 'Katalin Bettington', '59', '268 Alpine Circle', 'Blossom General Hospital', 'Jenna', 'Chinandega');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('02-6877139', 'Crin Stempe', '05', '5 West Parkway', 'Fairbanks Medical Center', 'Stone Corner', 'Pakemitan Dua');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('59-6087607', 'Allene Beushaw', '81', '288 Doe Crossing Circle', 'Blossom General Hospital', 'Debra', 'Santiago de María');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('24-9919009', 'Nerti Gabotti', '44', '37 Gale Pass', 'Blossom General Hospital', 'Rutledge', 'Taha Man Zu');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('85-7522922', 'Josiah Dyerson', '96', '073 Paget Street', 'Fairbanks Medical Center', 'Gina', 'Yanling');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('48-4234963', 'Blondy Olivella', '76', '4 Drewry Road', 'Fairbanks Medical Center', 'Birchwood', 'Kuta');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('16-3154214', 'Carena Mangeot', '94', '95259 Becker Street', 'Blossom General Hospital', 'Cody', 'Kertosari');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('44-1497029', 'Euell Mace', '82', '037 Milwaukee Point', 'Blossom General Hospital', 'Green Ridge', 'Xiaogang');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('49-5935073', 'Rhetta Caughey', '62', '749 Marcy Trail', 'Blossom General Hospital', 'Bartillon', 'Diamante');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('28-9486231', 'Iorgos Curthoys', '74', '06903 Upham Drive', 'Blossom General Hospital', 'Monument', 'Owo');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('27-1025319', 'Nicolea Le Guin', '21', '5 Pawling Plaza', 'Fairbanks Medical Center', 'Grasskamp', 'Železná Ruda');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('24-7661424', 'Phyllys O''Donnelly', '61', '2 Becker Center', 'Blossom General Hospital', 'Knutson', 'Trollhättan');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('69-4428949', 'Isidore Crathorne', '12', '21568 Thackeray Road', 'Hope Haven Community Hospital', 'Sugar', 'La Estancia');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('48-5754754', 'Cynthy Flagg', '00', '21308 Union Pass', 'Fairbanks Medical Center', 'Manufacturers', 'Jagistay');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('22-1556691', 'Cinnamon Ferreiro', '38', '78 Stone Corner Hill', 'Fairbanks Medical Center', 'Northland', 'Longjin');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('56-0365514', 'Rich Stelfax', '28', '434 Dorton Drive', 'Fairbanks Medical Center', 'Laurel', 'Meicheng');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('55-8956505', 'Tarrance Wrigglesworth', '40', '22837 Merry Point', 'Fairbanks Medical Center', 'Comanche', 'Patos de Minas');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('07-7927051', 'Eddy Wield', '84', '6 Mosinee Road', 'Fairbanks Medical Center', 'Mandrake', 'Espinal');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('70-2220566', 'Dannye Van de Vlies', '93', '0395 Village Green Circle', 'Fairbanks Medical Center', 'Bluejay', 'Tiwi');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('29-6389897', 'Ky Jirak', '76', '701 Pierstorff Drive', 'Fairbanks Medical Center', 'Forster', 'Shuigou');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('19-6476745', 'Deane Imlach', '17', '9 Jay Plaza', 'Fairbanks Medical Center', 'Village', 'Hikkaduwa');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('15-2426333', 'Bianka Pomphrey', '19', '093 Lunder Court', 'Fairbanks Medical Center', 'Burning Wood', 'Siak Sri Indrapura');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('70-6109455', 'Eachelle Ilyasov', '70', '3 Bashford Road', 'Fairbanks Medical Center', 'Namekagon', 'Usogorsk');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('87-2497809', 'Evvy MacQuist', '67', '3570 Delaware Plaza', 'Fairbanks Medical Center', 'Comanche', 'Maguling');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('99-1548877', 'Raymond Sparks', '26', '1 Toban Alley', 'Fairbanks Medical Center', 'Sachtjen', 'Shicheng');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('58-1753228', 'Brewer Hafner', '42', '9499 Tony Terrace', 'Fairbanks Medical Center', 'Oak', 'Saint Joseph');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('71-8574752', 'Karl Boarleyson', '16', '45 Becker Alley', 'Fairbanks Medical Center', 'Southridge', 'Majennang');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('88-3518681', 'Cordula Heeran', '44', '1438 Bay Hill', 'Blossom General Hospital', 'Paget', 'Lagny-sur-Marne');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('27-0420710', 'Charley Foss', '60', '719 Anniversary Court', 'Blossom General Hospital', 'Shasta', 'Yugang');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('13-4972414', 'Roz Pestell', '32', '24 Vera Terrace', 'Blossom General Hospital', 'Hintze', 'Chuangwang');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('01-0006946', 'Burgess Ferminger', '36', '347 Stoughton Drive', 'Grand River Medical Clinic', 'Jana', 'Sanhe');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('64-8487862', 'Rebe Coughlan', '35', '366 Esker Crossing', 'Fairbanks Medical Center', 'Golf', 'Adigeni');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('75-3296076', 'Mona Clow', '49', '45 Summer Ridge Crossing', 'Fairbanks Medical Center', 'Ludington', 'Carcavelos');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('38-7923078', 'Beth Jorczyk', '31', '3 Daystar Pass', 'Blossom General Hospital', 'Dakota', 'Oepula');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('48-3781645', 'Janessa Merchant', '01', '83 Scofield Way', 'Blossom General Hospital', 'East', 'Benito Juarez');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('44-5856214', 'Roger Glendining', '37', '484 Bowman Trail', 'Grand River Medical Clinic', 'Garrison', 'Shijing');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('47-1423619', 'Dorolice Okenden', '07', '9982 Buell Terrace', 'Fairbanks Medical Center', 'Garrison', 'Hlusk');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('80-3740991', 'Anneliese Howes', '61', '6776 Riverside Trail', 'Fairbanks Medical Center', 'Linden', 'Los Angeles');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('54-2278901', 'Parker Cust', '47', '6644 Sheridan Street', 'Blossom General Hospital', 'Anthes', 'Jiuzhen');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('60-8267549', 'Roy Kemet', '78', '94 Hanover Avenue', 'Fairbanks Medical Center', 'Sycamore', 'Ágios Spyrídon');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('90-7835531', 'Raquela Folliss', '58', '64 Nelson Plaza', 'Blossom General Hospital', 'Crest Line', 'Rio do Sul');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('84-7566341', 'Florette Fateley', '35', '2 Lerdahl Drive', 'Fairbanks Medical Center', 'Bunker Hill', 'Saint-Denis');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('31-4347654', 'Eliza Gear', '51', '38551 Morrow Place', 'Fairbanks Medical Center', 'Canary', 'Paris 11');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('14-4208810', 'Valry Earnshaw', '71', '075 Onsgard Hill', 'Fairbanks Medical Center', 'Warrior', 'Jargalant');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('56-4701538', 'Claudius Gravenor', '58', '815 Manitowish Trail', 'Fairbanks Medical Center', 'Sheridan', 'Phonsavan');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('47-1398750', 'Melvyn Marples', '73', '0914 Hauk Plaza', 'Grand River Medical Clinic', 'Moulton', 'Rū-ye Sang');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('52-9972631', 'Hanna Simkins', '47', '583 Granby Center', 'Blossom General Hospital', 'Schiller', 'Slavyanovo');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('01-5994699', 'Rachelle Scambler', '04', '3444 Jackson Way', 'Blossom General Hospital', '8th', 'Al Matlīn');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('40-0827383', 'Anabelle Klimt', '55', '311 Cody Court', 'Progress Hospital Center', 'Derek', 'Gulai');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('16-3352049', 'Claiborne Gavaran', '46', '59 Northfield Point', 'Fairbanks Medical Center', 'Anhalt', 'Trubchevsk');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('58-6625489', 'Kennett Hinchcliffe', '63', '40577 Marcy Terrace', 'Fairbanks Medical Center', 'Maryland', 'Liuzhou');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('46-4511150', 'Carrissa Yeskov', '18', '2 Bellgrove Pass', 'Fairbanks Medical Center', 'Sundown', 'Ordóñez');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('53-6433596', 'Loleta Capeloff', '29', '645 Sommers Alley', 'Fairbanks Medical Center', 'Schiller', 'Sieradza');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('06-1187029', 'Melony Girodias', '99', '68 Clemons Trail', 'Hope Haven Community Hospital', 'Arapahoe', 'Tlatah');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('61-3599267', 'Libby De Carteret', '82', '929 Sage Point', 'Hope Haven Community Hospital', 'Pearson', 'Mendeleyevo');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('41-3390010', 'Farleigh Bouttell', '66', '623 Holmberg Plaza', 'Fairbanks Medical Center', 'Rockefeller', 'Shiye');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('70-0774235', 'Maddalena Traise', '54', '7 Commercial Terrace', 'Fairbanks Medical Center', 'Sachs', 'Baranów');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('63-1396057', 'Petrina Marsden', '40', '12 Spenser Plaza', 'Fairbanks Medical Center', 'David', 'Huangshi');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('35-7817218', 'Rozelle Hiley', '32', '1 Crowley Alley', 'Fairbanks Medical Center', 'Lighthouse Bay', 'Ngawen');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('65-2650152', 'Silvan Reina', '38', '5515 Jackson Parkway', 'Blossom General Hospital', 'Redwing', 'Pietà');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('61-6349045', 'Todd Thacke', '40', '93437 Jackson Junction', 'Fairbanks Medical Center', 'Sheridan', 'Enewetak');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('28-6392274', 'Hamil Harverson', '45', '350 Express Court', 'Fairbanks Medical Center', 'Rusk', 'Watari');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('97-0841208', 'Jenica Athowe', '21', '5 Marcy Park', 'Blossom General Hospital', 'Kings', 'Sergiyev Posad');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('00-8053235', 'Daniella Gatehouse', '94', '3266 Moland Terrace', 'Blossom General Hospital', 'Stephen', 'Ngulakan');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('92-9950663', 'Oliy Truitt', '10', '7 Marcy Drive', 'Fairbanks Medical Center', 'North', 'Qal‘ah-ye Shahr');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('69-0309527', 'Darwin Burdoun', '64', '26 Northwestern Lane', 'Fairbanks Medical Center', 'Del Mar', 'Kriel');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('95-0383555', 'Kacie Clayfield', '28', '0 Bobwhite Park', 'Blossom General Hospital', 'Calypso', 'Alvaiázere');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('55-5625411', 'Remy McMichan', '99', '15581 Barby Place', 'Hope Haven Community Hospital', 'Corry', 'Hongyanxi');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('78-0608146', 'Nadean Loveday', '20', '4484 Ryan Place', 'Blossom General Hospital', 'Maryland', 'Xirikxiy');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('12-1917272', 'Franciskus Piens', '71', '5 Lyons Circle', 'Fairbanks Medical Center', 'Anderson', 'Grevená');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('42-2998423', 'Brucie Sentinella', '62', '6 Kinsman Center', 'Fairbanks Medical Center', 'Duke', 'Machachi');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('16-8983684', 'Enos Cansdill', '89', '9 Harper Place', 'Hope Haven Community Hospital', 'Randy', 'Ia Kha');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('65-0665377', 'Row Giacobbo', '91', '0485 Park Meadow Terrace', 'Hope Haven Community Hospital', 'Mitchell', 'Cherëmukhovo');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('88-9440462', 'Luci Pedrocco', '99', '371 Graedel Terrace', 'Grand River Medical Clinic', 'Boyd', 'Ribeirinha');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('10-0847333', 'Josefina Cranefield', '96', '78 Duke Crossing', 'Blossom General Hospital', 'Bluestem', 'Älvdalen');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('48-2903306', 'Tobey Manach', '14', '7193 Commercial Parkway', 'Fairbanks Medical Center', 'Carberry', 'Taoyuan');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('36-5113298', 'Chandal Arrighetti', '69', '2266 Golf View Hill', 'Fairbanks Medical Center', 'Hansons', 'Gabú');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('93-6658084', 'Cheri Moniker', '39', '399 Artisan Circle', 'Grand River Medical Clinic', 'Redwing', 'Preiļi');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('26-1580741', 'Boniface Wiper', '38', '3 Cambridge Parkway', 'Grand River Medical Clinic', 'Forest', 'Usukhchay');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('40-9335528', 'Stefa Sinnett', '24', '9021 Sachtjen Lane', 'Ruby Valley Hospital Center', 'Kennedy', 'Inda Silasē');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('69-5333618', 'Karalynn Hansell', '85', '752 Schurz Drive', 'Grand River Medical Clinic', 'Clove', 'Suvorovo');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('44-3672366', 'Westbrook Alison', '07', '38 Walton Circle', 'Fairbanks Medical Center', 'Commercial', 'Zelenogorsk');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('14-7922364', 'Sarajane Torel', '49', '4 Ronald Regan Circle', 'Fairbanks Medical Center', 'Hoffman', 'Mawu');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('41-6765594', 'Faber Lidgley', '08', '7517 Dawn Lane', 'Fairbanks Medical Center', 'Lakewood Gardens', 'Åstorp');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('11-2171660', 'Harli David', '03', '193 Hagan Center', 'Hope Haven Community Hospital', 'Hintze', 'Callahuanca');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('11-9278112', 'Uriah Dugan', '68', '1 Crest Line Court', 'Blossom General Hospital', 'Scoville', 'Curiapo');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('57-3265599', 'Torrie Heck', '02', '292 John Wall Park', 'Fairbanks Medical Center', 'Sundown', 'Palmas');
insert into PatientRegister (PatientId, Name, Age, Address, HospitalName, BranchName, City) values ('30-2776641', 'Alejandro Mirralls', '55', '898 Steensland Place', 'Fairbanks Medical Center', 'Gerald', 'Strančice');
